# Generated by Django 4.0.1 on 2022-01-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('branch', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='user/student')),
            ],
        ),
    ]
