# Generated by Django 4.0.1 on 2022-02-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('employee_id', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
