# Generated by Django 4.0.1 on 2022-03-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_address_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='address',
            name='employee_id',
            field=models.ManyToManyField(to='user.Employee'),
        ),
    ]
