# Generated by Django 4.0.1 on 2022-03-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_address_employee_id_address_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='employee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.employee'),
        ),
    ]
